[project]
name = 'contract'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.usdcx'

[contracts.FundX-test]
path = 'contracts/FundX.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
